#!/bin/sh -eu
# Get a value from hosted-ops us-west-2 SecretsManager

: "${SECRET_NAME:?Must specify a secret to retrieve}"

# Get the secret value then extract the first value from the JSON object that is returned
secret_value=$(aws secretsmanager get-secret-value --secret-id ${SECRET_NAME} --query SecretString --output text \
               | jq -r '[.[] ] | .[0]')
