FROM ubuntu:latest
RUN apt-get -y update
RUN apt-get -y install git jq wget

RUN wget https://github.com/mikefarah/yq/releases/download/v4.14.2/yq_linux_386.tar.gz -O - |\
  tar xz && mv yq_linux_386 /usr/bin/yq

RUN rm -rf ~/.ssh && mkdir -p ~/.ssh && ssh-keyscan github.com > ~/.ssh/known_hosts

COPY ./util /usr/local/bin

ARG DEPLOY_KEY_BASE64

RUN if test -n "${DEPLOY_KEY_BASE64}"; then /usr/local/bin/setup-github; fi


