#!/bin/sh -eu

: "${REPOSITORY:?Must specify a repository to clone}"

case $REPOSITORY in
  "aws-vault-config")
    echo "airplane/aws-vault-config-deploy-key-base64"
    ;;
  "hosted-aws-management")
    echo "airplane/hosted-aws-management-deploy-key-base64"
    ;;
  "hosted-deployments")
    echo "airplane/hosted-deployments-deploy-key-base64"
    ;;
  "staging-deployments")
    echo "airplane/staging-deployments-deploy-key-base64"
    ;;
  "conduit-deployments")
    echo "airplane/conduit-deployments-deploy-key-base64"
    ;;
  *)
    echo "Could not find GitHub deploy key for repository ${REPOSITORY}"
    exit 1
esac
