#!/bin/sh -eu

: ${DEPLOY_KEY_BASE64:?"DEPLOY_KEY_BASE64 required to setup-github"}

mkdir -p ~/.ssh

echo ${DEPLOY_KEY_BASE64} | base64 -d > ~/.ssh/id_github

chmod 600 ~/.ssh/id_github

cat << EOF > ~/.ssh/config
Host github.com
 HostName github.com
 IdentityFile ~/.ssh/id_github
EOF

git config --global user.name "Airplane"

ssh -T git@github.com || echo "ok"
