#!/bin/sh -eu

: ${DEPLOY_KEY_BASE64:?"DEPLOY_KEY_BASE64 required to setup-github"}

mkdir -p ~/.ssh
ssh-keyscan github.com > ~/.ssh/known_hosts

echo ${DEPLOY_KEY_BASE64} | base64 -d > ~/.ssh/id_github

chmod 600 ~/.ssh/id_github

cat << EOF > ~/.ssh/config
Host github.com
 HostName github.com
 IdentityFile ~/.ssh/id_github
EOF

git config --global user.email "github-service-account@runpanther.io"
git config --global user.name "Airplane"

ssh -T git@github.com || echo "ok"
