name: Airplane

on:
  push:
    branches:
      - main
      - airplane-github-action

jobs:
  deploy-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Airplane Tasks
        uses: airplanedev/airplane-deploy@v1
        with:
          # Add your API key as a secret: https://docs.github.com/en/actions/security-guides/encrypted-secrets.
          # Generate a new API key by running `airplane apikeys create <key name>` from the CLI.
          api-key: ${{ secrets.AIRPLANE_API_KEY }}
          team-id: tea20210928zowif1z
          task-directory: airplane
