name: CI

on:
  push:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: us-west-2
  AWS_REGION: us-west-2

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install cfn-lint
        run: |
          python -m pip install --upgrade pip
          pip install cfn-lint

      - name: Lint
        run: |
          cfn-lint lambda/template.yml  

      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::246537256134:role/CI
          aws-region: us-west-2
          role-session-name: hosted-ops-ci
      - name: SAM Deploy
        run: |
          cd lambda
          sam build --config-file samconfig.toml
          sam deploy --config-file samconfig.toml \
            --role-arn arn:aws:iam::246537256134:role/CFNServiceRole \
            --no-fail-on-empty-changeset
