name: Lambda CI

on:
  push:
    paths:
      - lambda/**

jobs:
  build-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        paths: [ "deploy_rc_and_ga" ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.6
      - name: Install Dependencies
        working-directory: lambda/${{ matrix.paths }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Compile all Python files
        working-directory: lambda/${{ matrix.paths }}
        if: github.ref != 'refs/heads/main'
        run: |
          python -m compileall .
      - name: Run tests in lambda/${{ matrix.paths }} directory
        working-directory: lambda/${{ matrix.paths }}
        run: |
          pytest -v
