name: Observability to Asana

on:
  push:
    paths:
    - 'sentry_asana/**'
    - 'Pipfile*'
    - 'scripts/**'
    - 'requirements.txt'
    - '.github/workflows/observability*.yml'

jobs:
  o11y-ci:
    name: o11y test and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Set up Pipenv for Python 3.9.14
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.14'
          cache: pipenv
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Install dependencies
        run: pipenv install --python 3.9.14  
      - name: Unit Tests
        run: pipenv run bash scripts/python_unit_test.sh
      - name: Lint Python
        run: pipenv run bash scripts/python_lint.sh
      - name: Lint YML
        run: pipenv run yamllint sentry_asana/src/common/components/entities/data/teams.yaml
