name: Observability to Asana

on:
  push:
    paths:
    - 'sentry-asana/**'
    - 'Pipfile*'
    - 'scripts/**'
    - 'requirements.txt'
    - '.github/workflows/observability*.yml'

jobs:
  o11y-ci:
    name: o11y test and lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Keep the full semver to match local dev and CI's environment
        python-version: ['3.9.14']
    steps:
      - uses: actions/checkout@v3
    
      - name: Set up Pipenv for Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pipenv
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Install dependencies
        run: pipenv install --python ${{ matrix.python-version }}    
      - name: Unit Tests
        run: pipenv run bash scripts/python_unit_test.sh
      - name: Lint Python
        run: pipenv run bash scripts/python_lint.sh
      - name: Lint YML
        run: pipenv run yamllint sentry_asana/src/common/components/entities/data/teams.yaml
